apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: fabricioveronez/web-page:green
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort
